%%%2009-04-24 msim4fit.m: to fit the simulation generated by msim4.m or
%%%real HX-MS data including two or more sub-populations:


%%%start from 'Distr' generated by msim4.m Case III


%%%double-Guassian fitting, get Area1, Mean1, Area2, Mean2,...


%%%to cal fraction of each sub-population:
% fraction1=Area1/sum(Areas); fraction2=Area2/sum.....


%%%to fit the (average) protection factor of each sub-population:
p0=1;
pf=lsqnonlin(@msim4fit_fit,p0);


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%in msim4fit_fit.m:

function f = msim4fit_fit(x)

disp('using kc(/min) of a-Syn Peptide_14-38 at 5"C pD4 H->D, generated by FBMME_HD_aSyn_WT.xls (first two residues kc=0): ')
kc=[0	0	0.07946	0.09268	0.05884	0.05884	0.20721	0.03137	0.02953	0.01725	0.03449	0.10156	0.12306	0.09268	0.20721	0.16848	0.05884	0.10156	0.02671	0.02953	0.01725	0.12199	0.29261	0.12306	0.02459
];

N=25;  %number of exchangable sites of each molecule (25 for Peptide14-38 of a-Syn)

T=30;   %HX time (min)

Y=0;
for i=1:N
    Y=Y+1-exp(-kc(i)*T/x);
end

f=Y-6.4 %6.4 is the Mean of a subpopulation from double-Gaussian fitting //! should replaced by 6.4/(allD/maxD) for real data

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%